#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl) -> @cosmaut:matrix.org      #
#  @DerFredy       -> @derfredy:matrix.org     #
#  @Bitcoinera -> @bitcoinera:matrix.org       #                               
#                                              #
################################################

key_name=$(docker exec -ti cyberd cyberdcli keys list | awk 'FNR==4{print $1}')
chain_id=`curl -s http://localhost:26657/status | jq -r '.result.node_info.network'`
cosmosvaloper=$(docker exec -ti cyberd cyberdcli keys show $key_name --bech=val | awk 'FNR==2{print $3}')

docker exec cyberd cyberdcli query staking validator $cosmosvaloper --chain-id=$chain_id --output=json | jq '.jailed'
