#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl) -> @cosmaut:matrix.org      #
#  @DerFredy       -> @derfredy:matrix.org     #
#  @Bitcoinera -> @bitcoinera:matrix.org       #                               
#                                              #
################################################

chain_id=`curl -s http://localhost:26657/status | jq -r '.result.node_info.network'`
key_name=$(docker exec -ti cyberd cyberdcli keys list | awk 'FNR==4{print $1}')

#
# Simple countdown timer
#
function countdown {
  #	
  # 2 days countdown in seconds	
  # 60s*60min*24h*1day
  # Here every one minute
  secs=$((60*1))
  while [ $secs -gt 0 ]; do
    echo -ne "Waiting $secs seconds \033[0K\r"
    sleep 1
    : $((secs--))
  done
}

#
# Read Wallet password
#

echo "Wallet password:"
read -s password

#
# Start de loop
#

while true
 do
  jailed=`~/scripts/jailed.sh`

  if [[ "${jailed}" == "true" ]]; then
    echo "Is Jailed? $jailed"

    echo ""
    echo "Freeing Validator:"
    echo ""
    echo "$password" | docker exec -i cyberd cyberdcli tx slashing unjail --from=$key_name --chain-id=$chain_id -y 
    echo "Done! Let's wait and see if we get in jail again (hopefully not)"

    countdown
  else
    echo "Cool! Let's wait and hope we don't get in jail anymore"
    countdown
  fi
done
